projeto-webmobile/anuncios/urls.py
from django.urls import path
from anuncios.views import *


urlpatterns = [
    path('', ListarAnuncios.as_view(), name='listar-anuncios'),
    path('novo/', CriarAnuncios.as_view(), name='criar-anuncios'),
    path('<int:pk>/', EditarAnuncios.as_view(), name='editar-anuncios'),
    path('deletar/<int:pk>/', DeletarAnuncios.as_view(), name='deletar-anuncios'),
    # API urls
    path('api/', APIListarAnuncios.as_view(), name='api-listar-anuncios'),
    path('criar/', APICriarAnuncios.as_view(), name='api-criar-anuncio'),
    path('editar/<int:pk>/', APIEditarAnuncios.as_view(), name='api-editar-anuncio'),
    path('deletar/<int:pk>/', APIDeletarAnuncios.as_view(), name='api-deletar-anuncio'),
]

projeto-webmobile/produtos/urls.py
from django.urls import path
from produtos.views import *

urlpatterns = [
    path('', ListarProdutos.as_view(), name='listar-produtos'),
    path('novo/', CriarProdutos.as_view(), name='novo-produtos'),
    path('edit/<int:pk>/', EditarProdutos.as_view(), name='editar-produtos'),
    path('delete/<int:pk>/', DeletarProdutos.as_view(), name='deletar-produtos'),
    path('fotos/<str:arquivo>/', FotoProdutos.as_view(), name='fotos-produtos'),
    # API urls
    path('api/', APIListarProdutos.as_view(), name='api-listar-produtos'),
    path('api/delete/<int:pk>/', APIDeletarProdutos.as_view(), name='api-deletar-produtos'),
    path('api/create/', APICriarProdutos.as_view(), name='api-criar-produto'),
    path('api/edit/<int:pk>/', APIEditarProdutos.as_view(), name='api-editar-produto'),

]

projeto-webmobile/tech_store/urls.py
from django.contrib import admin
from django.urls import path
from tech_store.views import *
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('autenticacao-api/', LoginAPI.as_view()),
    path('logout/', Logout.as_view(), name='logout'),
    path('produtos/', include('produtos.urls'), name='produtos'),
    path('anuncios/', include('anuncios.urls'), name='anuncios'),

]

projeto-webmobile/produtos/models.py
from django.db import models
from produtos.consts import *

class Produtos(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.CharField(max_length=600)
    estado = models.SmallIntegerField(choices=OPCOES_ESTADO)
    categoria = models.SmallIntegerField(choices=OPCOES_CATEGORIAS)
    foto = models.ImageField(blank=True, null=True, upload_to='produtos/fotos')

projeto-webmobile/produtos/forms.py
from django.forms import ModelForm
from produtos.models import Produtos

class FormularioProdutos(ModelForm):
    # Formulario para o model veiculo
    class Meta:
        model = Produtos
        exclude = []

projeto-webmobile/produtos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse, Http404
from django.shortcuts import get_object_or_404
from django.views.generic import View, CreateView, ListView, DeleteView, UpdateView
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy
from rest_framework.generics import ListAPIView, DestroyAPIView
from rest_framework import permissions
from rest_framework.authentication import TokenAuthentication
from produtos.forms import FormularioProdutos
from produtos.models import Produtos
from produtos.serializers import SerializadorProdutos
from rest_framework import generics

# Create your views here.
class ListarProdutos(LoginRequiredMixin, ListView):
    # Views para listar produtos cadastrados
    model = Produtos
    context_object_name = 'produtos'
    template_name = 'produtos/listar.html'


class FotoProdutos(LoginRequiredMixin, View):
    def get(self, request, arquivo):
        try:
            produtos = Produtos.objects.get(foto='produtos/fotos/{}'.format(arquivo)) 
            return FileResponse(produtos.foto)
        except ObjectDoesNotExist as exc:
            raise Http404("Foto não encontrada") from exc
        except Exception as exception:
            raise exception

class CriarProdutos(LoginRequiredMixin, CreateView):
    model = Produtos
    form_class = FormularioProdutos
    template_name = 'produtos/novo.html'
    success_url = reverse_lazy('listar-produtos')

class EditarProdutos(LoginRequiredMixin, UpdateView):
    model = Produtos
    form_class = FormularioProdutos
    template_name = 'produtos/edit.html'
    success_url = reverse_lazy('listar-produtos')

class DeletarProdutos(LoginRequiredMixin, DeleteView):
    model = Produtos
    template_name = 'produtos/delete.html'
    success_url = reverse_lazy('listar-produtos')

    def get_object(self):
        return get_object_or_404(Produtos, pk=self.kwargs['pk'])
    
# API's -------------------------------------------------------------------------------------
    
class APIListarProdutos(ListAPIView):
    """
    view para listar instancias de produtos (por meio da API REST)
    """
    serializer_class = SerializadorProdutos
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Produtos.objects.all()
    
class APICriarProdutos(generics.CreateAPIView):
    """
    View para criar novos produtos via API.
    """
    queryset = Produtos.objects.all()
    serializer_class = SerializadorProdutos
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

class APIEditarProdutos(generics.UpdateAPIView):
    """
    View para editar produtos via API.
    """
    queryset = Produtos.objects.all()
    serializer_class = SerializadorProdutos
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]
    
    def get_object(self):
        # Recupera o produto a partir do ID da URL
        return Produtos.objects.get(pk=self.kwargs['pk'])

class APIDeletarProdutos(DestroyAPIView):
    """
    View para deletar instâncias de veículos (por meio da API REST)
    """
    serializer_class = SerializadorProdutos
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Produtos.objects.all()

projeto-webmobile/templates/produtos/delete.html
{% extends '../base.html' %}

{% load static %}

{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block title %}Deletar Veículo{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Deletar Veículo</h2>
    
    <div class="alert alert-warning">
        <h4 class="alert-heading">Confirmação de Deleção</h4>
        <p>Tem certeza de que deseja deletar o produto <strong>{{ produtos.titulo }} {{ produtos.descricao }} ({{ produtos.categoria }})</strong>?</p>
        <p>Essa ação não poderá ser desfeita.</p>
    </div>

    <form action="{% url 'deletar-produtos' produtos.pk %}" method="post">
        {% csrf_token %}
        <div class="d-flex justify-content-between">
            <a href="{% url 'listar-produtos' %}" class="btn btn-secondary">
                <i class="bi bi-arrow-left-circle"></i> Cancelar
            </a>
            <button type="submit" class="btn btn-danger">
                <i class="bi bi-trash"></i> Deletar
            </button>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

projeto-webmobile/templates/produtos/edit.html
{% extends '../base.html' %}

{% load static %}

{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block title %}Editar Produto{% endblock %}

{% block list %}
<div class="container mt-5" style="max-width: 1200px;">
    <h2 class="mb-4 text-center">Editar Produto</h2>
    <form action="{% url 'editar-produtos' produtos.pk %}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}

        <div class="row mb-4">
            <!-- Título -->
            <div class="col-md-6">
                <div class="card-edit">
                    <label for="id_titulo" class="form-label fs-4 fw-bold">Título Atual:</label>
                    <h4>{{ produtos.titulo }}</h4>
                    <label for="id_titulo" class="form-label fs-4 fw-bold">Novo Título:</label>
                    {{ form.titulo }}
                </div>
            </div>

            <!-- Descrição -->
            <div class="col-md-6">
                <div class="card-edit">
                    <label for="id_descricao" class="form-label fs-4 fw-bold">Descrição Atual:</label>
                    <p>{{ produtos.descricao }}</p>
                    <label for="id_descricao" class="form-label fs-4 fw-bold">Nova Descrição:</label>
                    {{ form.descricao }}
                </div>
            </div>
        </div>

        <div class="row mb-4">
            <!-- Categoria -->
            <div class="col-md-6">
                <div class="card-edit">
                    <label for="id_categoria" class="form-label fs-4 fw-bold">Categoria Atual:</label>
                    <p>{{ produtos.categoria }}</p>
                    <label for="id_categoria" class="form-label fs-4 fw-bold">Nova Categoria:</label>
                    {{ form.categoria }}
                </div>
            </div>

            <!-- Estado -->
            <div class="col-md-6">
                <div class="card-edit">
                    <label for="id_estado" class="form-label fs-4 fw-bold">Estado Atual:</label>
                    <p>{{ produtos.estado }}</p>
                    <label for="id_estado" class="form-label fs-4 fw-bold">Novo Estado:</label>
                    {{ form.estado }}
                </div>
            </div>
        </div>

        <div class="row mb-4">
            <!-- Foto -->
            <div class="col-md-6">
                <div class="card-edit">
                    <label for="id_foto" class="form-label fs-4 fw-bold">Foto Atual:</label>
                    <div class="img-edit">
                        {% if produtos.foto %}
                            <img  src="{{ produtos.foto.url }}" alt="Imagem do Produto" class="img-fluid" style="max-width: 100%; height: auto;">
                        {% else %}
                            <p>Sem foto atual.</p>
                        {% endif %}
                    </div>
                    <label for="id_foto" class="form-label fs-4 fw-bold mt-2">Nova Foto:</label>
                    {{ form.foto }}
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-center mt-4">
            <button type="submit" class="btn btn-primary me-2">Salvar Alterações</button>
            <a href="{% url 'listar-produtos' %}" class="btn btn-danger">Cancelar</a>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

projeto-webmobile/templates/produtos/listar.html
{% extends '../base.html' %}

{% load static %}

{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block title %}Listagem de Produtos{% endblock %}

<p>Total de produtos: {{ produtos|length }}</p>

{% block list %}
<div class="div-lista">
    <h1 class="text-center mb-4">Lista de Produtos</h1>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
        {% for p in produtos %}
        <div class="col">
            <div class="card" style="width: 18rem;">
              <div class="card-img-container">
                  <img class="card-img-top" src="{{ p.foto.url }}" alt="{{ p.titulo }}">
              </div>
              <div class="card-body">
                  <h5 class="card-title">{{ p.titulo }}</h5>
                  <div class="card-button"> 
                    <a href="#" class="btn btn-custom" data-bs-toggle="modal" data-bs-target="#modalDetalhes{{ p.id }}">Mais opções</a>
                  </div>
              </div>
          </div>
        </div>

        <!-- Modal Detalhes -->
        <div class="modal fade" id="modalDetalhes{{ p.id }}" tabindex="-1" aria-labelledby="modalDetalhesLabel{{ p.id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalDetalhesLabel{{ p.id }}">{{ p.titulo }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-6">
                                {% if p.foto %}
                                <img class="img-fluid" src="{{ p.foto.url }}" alt="{{ p.titulo }}">
                                {% else %}
                                <img class="img-fluid" src="{% static 'default-image.jpg' %}" alt="Imagem padrão">
                                {% endif %}
                            </div>
                            <div class="col-md-6">
                                <p><strong>Descrição:</strong> {{ p.descricao }}</p>
                                <p><strong>Estado:</strong> {{ p.get_estado_display }}</p>
                                <p><strong>Categoria:</strong> {{ p.get_categoria_display }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="{% url 'editar-produtos' p.id %}" class="btn btn-primary">Editar</a>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalDeletar{{ p.id }}">Excluir</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal Deletar -->
        <div class="modal fade" id="modalDeletar{{ p.id }}" tabindex="-1" aria-labelledby="modalDeletarLabel{{ p.id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalDeletarLabel{{ p.id }}">Deletar Produto</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>Tem certeza de que deseja deletar o produto <strong>{{ p.titulo }}</strong>?</p>
                        <p>Essa ação não poderá ser desfeita.</p>
                        <form action="{% url 'deletar-produtos' p.id %}" method="post">
                            {% csrf_token %}
                            <div class="d-flex justify-content-end">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-danger ms-2">Deletar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

projeto-webmobile/templates/produtos/novo.html
{% extends '../base.html' %}

{% load static %}

{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block title %}Criar Produto{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Criar Novo Produto</h2>
    <form action="{% url 'novo-produtos' %}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_titulo" class="form-label">Título</label>
                {{ form.titulo }}
            </div>

            <div class="col-md-6 mb-3">
                <label for="id_descricao" class="form-label">Descrição</label>
                {{ form.descricao }}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_estado" class="form-label">Estado</label>
                {{ form.estado }}
            </div>

            <div class="col-md-6 mb-3">
                <label for="id_categoria" class="form-label">Categoria</label>
                {{ form.categoria }}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="id_foto" class="form-label">Foto</label>
                {{ form.foto }}
            </div>
        </div>

        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Criar Produto</button>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}